language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm run test:coverage:ci
before_deploy:
  - npm run build